/*
包含n个mutation的type名称常量
 */
// export const RECEIVE_ADDRESS = 'receive_address'
export const RECEIVE_SWIPER = 'receive_swiper'
export const RECEIVE_CATEGORY = 'receive_category'
export const RECEIVE_RECOMMEND = 'receive_recommend'
export const RECEIVE_AREA = 'receive_area'
export const RECEIVE_ENTERPRISE = 'receive_enterprise'
export const RECEIVE_PRODUCT = 'receive_product'
export const RECEIVE_USERINFO = 'receive_userinfo'
export const RET_USERINFO = 'RET_USERINFO'
export const RECEIVE_SHOPCART = 'receive_shopcart'
export const INCREMENT_SHOP_COUNT = 'increment_shop_count'
export const DECREMENT_SHOP_COUNT = 'decrement_shop_count'
export const CLEAR_SHOPCART = 'clear_shopcart'
export const RECEIVE_ADDRESS = 'receive_address'
export const RECEIVE_ORDER = 'receive_order'
export const RECEIVE_ALLORDER = 'receive_allorder'
export const RECEIVE_ALLUSER = 'receive_alluser'
export const RECEIVE_ALLUSERS = 'receive_allusers'
export const RECEIVE_ALLADDRESS = 'receive_alladdress'
